const express = require("express");
const router = express.Router();
const Registration = require("../../controllers/registrationController");
const Login = require("../../controllers/loginController");
const OtpMatch = require("../../controllers/emailVarificationOtpMatch");
//const { merchantController } = require("../../controllers/merchantController");
router.post("/registration", Registration);
router.post("/login", Login);
router.post("/emailVarificationOtpMatch", OtpMatch);
//router.post("/merchant", merchantController);
module.exports = router;
